import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TheHeader  from '../components/theHeader'
import TheHome from './Home/index'
import TheAbout from '../components/TheAbout'
import TheFooter from '../components/TheFooter'                                                                       
import TheSkill from '../components/TheSkill' 


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TheHeader/>
      <main>
      <TheAbout/>
      <TheHome/>
     
          <TheSkill/>
          
      </main>

      <footer className={styles.footer}>
      <TheFooter/>
      </footer>
    </div>
  )
}
